### ISSUE TITLE
SignPictures does not work with Quark mod

### ISSUE THREAD

**Issue by Image64Labs** [Team-Fruit/SignPicture#44] opened 2018-10-24 00:33 UTC
Quark changes the way signs are handled and it would be nice to have support for the mod so it can be used with

**Comment by TheDeviantCrafter** [comment] 2019-02-23 01:54
This is a duplicate of #38. It can be fixed by disabling Quark's improved sign editing via config.

**Closed** 2019-02-23 02:06 UTC
Labels: duplicate, other mods compatibility
