### ISSUE TITLE
SignPicture - unsupported picture parameters everytime

### ISSUE THREAD

**Issue by Dushess** [Team-Fruit/SignPicture#7] opened 2016-11-26 11:03 UTC
For this time i just pasted a picture from reddit (jpg, 100x300) and without any changes i see this:
![2016-11-26_13 58 21](https://cloud.githubusercontent.com/assets/15954961/20639877/3c042218-b3e9-11e6-8761-795048d6e85e.png)
Maybe supported only pictures with sizes in precise 1:1 or 1:2 ratio сonsidering original texture sizes? (can be written in a block or few blocks)

I still forsed to set size and shifting manually, because buttons still working only in -1, 0 and 1 space.
in additional i set in config folder to current "signpic" in .minecraft and raise limits to 1024x1024, but after placing that tree picture on the wall.

**Comment by sjcl** [comment] 2016-11-26 11:19
You can maintain the aspect ratio of the original image by leaving the size as '?'. also, each adjustment button can be finely adjusted by clicking while holding down the shift control.

**Comment by Dushess** [comment] 2016-11-26 11:34
It seems that buttons doing nothing.
![2016-11-26_14 33 10](https://cloud.githubusercontent.com/assets/15954961/20640005/c2b57d9e-b3ed-11e6-8aba-b475e919272a.png)
![2016-11-26_14 32 59](https://cloud.githubusercontent.com/assets/15954961/20640004/c2a47a62-b3ed-11e6-8dfd-23c8b3b9bf47.png)

**Comment by Kamesuta** [comment] 2016-11-26 11:35
![Aspected Image](https://i.gyazo.com/20b7c6b75c2c7205e681b3f33cdbb501.png)
By specifying only one, you can resize while keeping the aspect ratio of the image. If you want to resize at your preferred ratio, please calculate and respond to both W and H.
In addition, you can adjust the adjustment button by 0.01 when holding down Shift, while pressing Ctrl, you can adjust it by 0.01.
![Adjustment Button](https://i.gyazo.com/4ba03e5cfa746f0de34bc5096cf4cf6a.gif)

**Comment by Dushess** [comment] 2016-11-26 11:37
On my side pressing any buttons gives me only -1, 0, 1 (for both integer and fractional)

**Comment by sjcl** [comment] 2016-11-26 11:38
![db0f3ff85a6af7282c28139773c35f75](https://cloud.githubusercontent.com/assets/16951483/20640043/33ed0dcc-b418-11e6-9004-28c377e1343c.png)
I can not reproduce the same phenomenon here ...

**Comment by Dushess** [comment] 2016-11-26 11:40
Uhuh, it comes on my installation.
![2016-11-26_14 38 27](https://cloud.githubusercontent.com/assets/15954961/20640055/9378f6f4-b3ee-11e6-84ef-665d6d1fdb3d.png)
![2016-11-26_14 38 38](https://cloud.githubusercontent.com/assets/15954961/20640059/9cbd508e-b3ee-11e6-9b03-f00fd69bbcea.png)


Will try on Win 7 later.

**Comment by Dushess** [comment] 2016-11-26 11:47
Hmm, how it will be here from normal contitions? Can you place this image with custom properties (center inside one block and Z=0.45) and give wy this map, i want see, will it save or not.

**Comment by sjcl** [comment] 2016-11-26 12:03
It is probably not an OS issue ... I developed on Win 10 and it works normally.

**Comment by Dushess** [comment] 2016-11-26 12:10
I tried Optifine D3 and D4, on XP with Forge 2099 (1.10.2), it works like before CTM fix, and my chiseled blocks from Chisels&Bits still invisible, but same versions on Win 7 is good, i don't know, what wrong there.

**Comment by sjcl** [comment] 2016-11-26 15:05
Hmm, I tried various things here, but I can not reproduce it. Other Mod may be affecting it.

**Comment by Dushess** [comment] 2016-11-26 15:27
Right, will check.

**Comment by sjcl** [comment] 2016-11-26 15:37
If you provide a list of Mod, we will verify here.

**Comment by Dushess** [comment] 2016-11-26 15:49
FRSM
Chisels&Bits
FenceOverhaul
Better Foliage
Bagelsmore
Architecture Craft
Paintings++
FakeBlocks
Malisis mods
More foods
Parcels and Packages
Rockhoundeig- hemistry
Precise time
Tree chopper

**Comment by Dushess** [comment] 2016-11-27 08:44
Yes, i checking that mod on my side.

**Comment by sjcl** [comment] 2016-11-27 18:16
I don't understand the detailed cause, but I tried to rewrite the part that seemed likely. 
[SignPicture-1.10.2-2.5.2.alpha-universal.zip](https://github.com/Team-Fruit/SignPicture/files/614884/SignPicture-1.10.2-2.5.2.alpha-universal.zip)

But I'm not confident that this problem will be fixed ...

**Comment by Dushess** [comment] 2016-11-27 19:45
No changes

**Comment by Dushess** [comment] 2016-11-27 19:49
As I understand, now this mod on me after place picture cannot move it to any value, only 0.5 by all direction. Also picture can be placed only autosized to 3 blocks width (stock). Buttons still rewrites data in fields (note: they skipping 0) instead of increment/decrament variable.

**Comment by sjcl** [comment] 2016-11-29 06:38
We made various tests, but I do not know the cause ... 
Can you screenshot the contents written on the sign in View Sign Mode?

**Comment by Dushess** [comment] 2016-11-29 07:04
Yes, a bit later.

**Comment by Kamesuta** [comment] 2016-11-30 08:26
From the screenshot's point of view, this bug seems to be caused by the dependency of the java standard library DecimalFormat used by SignPicture on country languages. It is thought that this is caused by using "," instead of "." As a decimal separator in France and several languages. "," Is handled as a parameter that is not supported by SignPicture, so it seems that it was displayed as UnsupportedSignPicture. When you tried with a different PC it is considered that the decimal point delimiter on that PC succeeded using ".".
Please try α version which solved this problem.
[SignPicture-1.10.2-2.5.3.alpha-universal.zip](https://github.com/Team-Fruit/SignPicture/files/621251/SignPicture-1.10.2-2.5.3.alpha-universal.zip)

---
スクリーンショットから見て、このバグは、SignPictureが使用している、DecimalFormatというjava標準ライブラリが、国の言語に依存するために発生したものだと考えられます。これは、フランスやいくつかの言語の国では、小数点の区切りとして「.」ではなく、「,」を使用していることによるものだと考えられます。「,」はSignPictureでは対応していないパラメーターとして扱われるため、UnsupportedSignPictureと表示されたと考えられます。あなたが違うPCで試したとき成功したのはそのPCでの小数点の区切り文字が「.」を使用しているものだと考えられます。
この問題を解決したαバージョンをお試しください。

**Comment by Dushess** [comment] 2016-11-30 08:51
It works, many thanks.

**Closed** 2016-11-30 08:51 UTC
