### ISSUE TITLE
Sign Picture not working in smp server

### ISSUE THREAD

**Issue by ccar795** [Team-Fruit/SignPicture#1] opened 2016-09-27 04:15 UTC
Hello, great mod and all but it's not compatible with Optifine 1.8.9 H6 version as the signs are invisible. Also when trying on an smp server I go on it does not work. I place the sign down and no picture. This is with optifine version H5 which works with your mod.

https://gyazo.com/e7ff6751d730f8066bbc5eeebe4c9990

**Comment by Kamesuta** [comment] 2016-09-27 05:47
Thanks for reporting.
I have a Minecraft 1.8.9 and SignPicture 2.2.2 and Optifine U6 tried to experiment with SMP, it was not able to reproduce the situation.
Optifine settings and, because it might affect the other Mod, or sorry to trouble you, but you please examine the Mod to compete again?

---
私はMinecraft 1.8.9とSignPicture 2.2.2とOptifine U6をSMPでいろいろ試してみましたが、その状況を再現することができませんでした。
Optifineの設定や、ほかのModの影響かもしれませんので、お手数ですがもう一度競合するModを調べてもらえませんか？

https://gyazo.com/e39e65f4bb1a37f48664d16fa5905711

**Comment by ccar795** [comment] 2016-09-27 07:43
Okay I tested on a local server I created and it works fine. Kotaserver is a spigot server so that could be the issue here.
![2016-09-27_00 41 02](https://cloud.githubusercontent.com/assets/21349871/18864477/5d5e7012-844b-11e6-8d87-d0494e6258f0.png)

**Comment by Kamesuta** [comment] 2016-09-27 14:48
I've checked in Kotaserver. I found NoCheatPlus is installed in server. The improvement try attempt so that it is not detected in the NoCheatPlus.

**Comment by ccar795** [comment] 2016-09-27 20:53
Ok thanks for logging on and taking a look yourself with help from kotarobo_san.

**Comment by Kamesuta** [comment] 2016-09-28 16:25
[SignPicture2.3.0](https://github.com/Team-Fruit/SignPicture/releases/tag/1.8.9-2.3.0) Released!
Since the implementation of the Anti-AutoSign measures I think that it can be installed even KotaServer.

**Comment by ccar795** [comment] 2016-09-29 01:56
It works! You're the best man. Thank you. ![2016-09-28_18 55 01](https://cloud.githubusercontent.com/assets/21349871/18938389/232ec3a2-85ad-11e6-9289-ae021b8deff4.png)

**Comment by Kamesuta** [comment] 2016-09-29 02:19
Please, go enjoy this mod.
Have a nice day! xD

**Closed by Kamesuta** 2016-09-29 02:19 UTC
